name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  cmdstanVersion: "2.34.0"

jobs:
  build:
    name: Continuous Integration
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.10"
          cache: pip
      - name: "Install Python dependencies"
        run: pip install -r requirements.txt
      - name: "Cache cmdstan"
        uses: actions/cache@v4
        with:
          path: /home/runner/.cmdstan
          key: cmdstan-${{ env.cmdstanVersion }}
      - name: "Install cmdstan"
        run: python -m cmdstanpy.install_cmdstan --version ${{ env.cmdstanVersion }}
      - name: "Build the project"
        run: "make build"
        env:
          # Our tests may contain a number of stochastic elements. Setting a seed will make sure
          # they're not flaky (but also hide potential issues).
          SEED: "0"
